version: '3.8'

services:
  lightrag-extended:
    build: 
      context: .
      dockerfile: Dockerfile.extended  # Use the extended Dockerfile
    ports:
      - "9621:9621"
    volumes:
      - ./data:/app/data
      - ./config.ini:/app/config.ini
      - ./custom_api_extension.py:/app/custom_api/custom_api_extension.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-ada-002}
      - WORKING_DIR=/app/data/rag_storage
      - INPUT_DIR=/app/data/inputs
      - HOST=0.0.0.0
      - PORT=9621
      # Optional: Add authentication
      - LIGHTRAG_API_KEY=${LIGHTRAG_API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9621/python-api/status"]
      interval: 30s
      timeout: 10s
      retries: 3