version: '3.8'

services:
  lightrag:
    build: .
    ports:
      - "9621:9621"
    volumes:
      - ./data:/app/data
      - ./lightrag_extended_api.py:/app/lightrag_extended_api.py
      - ./migrate_metadata.py:/app/migrate_metadata.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-ada-002}
      - WORKING_DIR=/app/data/rag_storage
      - HOST=0.0.0.0
      - PORT=9621
    restart: unless-stopped