name: lightrag-app
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/your-repo-name
  http_port: 9621
  instance_count: 1
  instance_size_slug: basic-s
  name: lightrag
  routes:
  - path: /
  run_command: python /app/startup_wrapper.py
  source_dir: /
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_BASE_URL
    scope: RUN_TIME
    value: https://api.openai.com/v1
  - key: LLM_MODEL
    scope: RUN_TIME
    value: gpt-4o-mini
  - key: EMBEDDING_MODEL
    scope: RUN_TIME
    value: text-embedding-ada-002
  - key: WORKING_DIR
    scope: RUN_TIME
    value: /app/data/rag_storage
  - key: HOST
    scope: RUN_TIME
    value: 0.0.0.0
  - key: PORT
    scope: RUN_TIME
    value: "9621"
  - key: WEBUI_ENABLED
    scope: RUN_TIME
    value: "true"